### ISSUE TITLE
Back End - build model for view rugs page

### ISSUE THREAD

**Issue by manorthcutt** [manorthcutt/project2#23]

**Comment by dodgen92** [comment]
`module.exports = function(sequelize, DataTypes) {
  var Rugs = sequelize.define("Rugs", {
    origin: DataTypes.STRING,
    type: DataTypes.STRING,
    size: DataTypes.STRING,
    price: DataTypes.INTEGER,
    condition: DataTypes.STRING,
    age: DataTypes.INTEGER
  });
  return Rugs;
};
`

**Comment by manorthcutt** [comment]
this task is complete
