### ISSUE TITLE
Design - Identify data points to capture

### ISSUE THREAD

**Issue by manorthcutt** [manorthcutt/project2#4]

**Comment by dodgen92** [comment]
Products database:
Type, Origin, Price, Condition, Size, Condition, Price

Users database:
Buyers, Sellers, Service

**Comment by manorthcutt** [comment]
Tyler - we will need to add a table to capture the sales transaction, a message sent from the buyer to the seller of a rug from the Buy.html page and a service request.

**Comment by manorthcutt** [comment]
We are going to icebox the sales transaction and messaging tasks for now.
