### ISSUE TITLE
Front End - Style the Home page

### ISSUE THREAD

**Issue by manorthcutt** [manorthcutt/project2#7]

**Comment by habibtaghavi08** [comment]
working on this and will be committing very soon as I link my pages and files together

**Comment by habibtaghavi08** [comment]
I'm gonna commit regardless yall don't have to accept the changes!! I believe it is what's been causing me the issue 

because I can't get it to show on localhost but I can on the default browser

**Comment by habibtaghavi08** [comment]
After I will try and pull again to see what the problem is

**Comment by habibtaghavi08** [comment]
also will leave a full Html file along with JavaScript and CSS for a money converter so people from all around the world can post their rugs on this site! may want to make a note on the For Sale input pg that all prices need to be converted into USD first and  maybe Euros not sure we will discuss it and leave USD only or add Euros as well, but make it the only way to post so the have to use the money converter and make it the only way to post is by choosing USD and but not or euros so either both or just the USD

**Comment by manorthcutt** [comment]
completed by Saudi and Habib
